**Dataframe:** A DataFrame represents a rectangular table of data and contains an ordered, named collection of columns, each of which can be a different value type (numeric, string, Boolean, etc.). The DataFrame has both a row and column index; it can be thought of as a dictionary of Series all sharing the same index.

* While a DataFrame is physically two-dimensional, you can use it to represent higher dimensional data in a tabular format using hierarchical indexing

### Table 5.1: Possible Data Inputs to the DataFrame Constructor

| Type                                  | Notes                                                                 |
|---------------------------------------|----------------------------------------------------------------------|
| 2D ndarray                            | A matrix of data, passing optional row and column labels             |
| Dictionary of arrays, lists, or tuples| Each sequence becomes a column; all sequences must be the same length|
| NumPy structured/record array         | Treated as the “dictionary of arrays” case                           |
| Dictionary of Series                  | Each value becomes a column; indexes are unioned to form row index   |
| Dictionary of dictionaries            | Each inner dictionary becomes a column; keys are unioned as row index|
| List of dictionaries or Series        | Each item becomes a row; union of keys/indexes become columns        |
| List of lists or tuples               | Treated as the “2D ndarray” case                                     |
| Another DataFrame                     | Uses existing indexes unless new ones are provided                   |
| NumPy MaskedArray                     | Like “2D ndarray” but masked values become missing data              |

In [1]:
import numpy as np
import pandas as pd

In [5]:
df1 = pd.DataFrame({'a':[1,2,3,4], 'b':[4,5,6, 7]})
print(df1)

   a  b
0  1  4
1  2  5
2  3  6
3  4  7

In [6]:
#print colums
df1["a"]

0    1
1    2
2    3
3    4
Name: a, dtype: int64

In [9]:
df1[["a","b"]]

   a  b
0  1  4
1  2  5
2  3  6
3  4  7

In [10]:
# print rows
df1.loc[1]

a    2
b    5
Name: 1, dtype: int64

In [11]:
df1.loc[1:3]

   a  b
1  2  5
2  3  6
3  4  7

In [14]:
# select both rows and columns
df1.loc[1:5, "b"]

1    5
2    6
3    7
Name: b, dtype: int64

In [19]:
df1.iloc[0:2]

   a  b
0  1  4
1  2  5

In [24]:
df1.head()

   a  b
0  1  4
1  2  5
2  3  6
3  4  7

In [26]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       4 non-null      int64
 1   b       4 non-null      int64
dtypes: int64(2)
memory usage: 192.0 bytes

In [27]:
df1.describe()

              a         b
count  4.000000  4.000000
mean   2.500000  5.500000
std    1.290994  1.290994
min    1.000000  4.000000
25%    1.750000  4.750000
50%    2.500000  5.500000
75%    3.250000  6.250000
max    4.000000  7.000000

In [32]:
# Add a column
df1["isGreaterthan3"] = df1["b"] >3

In [33]:
df1

   a  b  isGreaterthan3
0  1  4            True
1  2  5            True
2  3  6            True
3  4  7            True

In [34]:
# delete column
del df1["isGreaterthan3"]

In [31]:
df1

   a  b
0  1  4
1  2  5
2  3  6
3  4  7

In [35]:
df1.columns

Index(['a', 'b'], dtype='object')

In [36]:
#transpose the datafram
df1.T

   0  1  2  3
a  1  2  3  4
b  4  5  6  7

In [37]:
df1.to_numpy() # return as 2D array

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])